# App version, configurable by environment variable
app.version=${APP_VERSION:unknown}
quarkus.http.auth.form.http-only-cookie=false
quarkus.mongodb.connection-string = mongodb://localhost:27017
quarkus.mongodb.database = example-db
quarkus.banner.path=banner.txt
# Jackson configuration - exclude null fields from JSON responses
quarkus.jackson.serialization-inclusion=non-null

# TDL configuration
tdl.provider.name=The Digital Library
tld.service=qmusic
auth-api-tdl/mp-rest/url=https://auth.${tld.service}.com
tdl-api/mp-rest/url=https://api.${tld.service}hifi.com
tdl.origin.header=http://listen.${tld.service}.com
tdl.country.code=AR
tdl.cover.url=https://resources.${tld.service}.com/images/%s/%s
tdl.client.id=
tdl.refresh.token=

quarkus.log.category."org.jboss.resteasy.reactive.server.handlers".level=OFF

# jwks configuration for dev profile
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=*
%dev.smallrye.jwt.verify.key-format=JWK
%dev.smallrye.jwt.verify.algorithm=HS256
%dev.smallrye.jwt.verify.key.location=classpath:secret.jwk