name: CI Build-Publish native image with Quarkus CLI

# Define the events that trigger the workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (M.m.p)
        required: true

jobs:
  docker:
    # Define the operating systems and architectures to run the job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare metadata and timestamps
      - name: Prepare
        id: prep
        run: |
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "image_name=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-native" >> $GITHUB_OUTPUT

      # Set up GraalVM environment
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.TOKEN_GITHUB }}
          native-image-job-reports: 'true'

      # Install JBang and Quarkus CLI
      - name: Install JBang and Quarkus CLI
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
          echo "PATH=$PATH:/home/runner/.jbang/bin" >> $GITHUB_ENV

      # Verify the installation of Quarkus CLI
      - name: Verify Quarkus CLI installation
        run: quarkus --version

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Verify Docker Hub login
      - name: Verify Docker Hub Login
        run: |
          docker info
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< "${{ secrets.DOCKER_TOKEN }}"
          echo "Docker login verification completed"

      # Create repository if it doesn't exist (optional)
      - name: Create Docker Hub repository if not exists
        run: |
          # You might need to use Docker Hub API to create a repository if it doesn't exist
          echo "Checking/creating repository: ${{ steps.prep.outputs.image_name }}"
          # This step is optional and depends on your Docker Hub setup

      # Build the native artifact
      - name: Build Native Artifact
        run: |
          quarkus build --native
          ls -la target/

      # Build the native image and push the Docker image
      - name: Build Native Image and Push Docker Image
        run: |
          echo "Building image for platform: ${{ matrix.platform }}"
          IMAGE_TAG="${{ steps.prep.outputs.image_name }}:${{ github.event.inputs.version }}-${{ matrix.platform }}"
          LATEST_TAG="${{ steps.prep.outputs.image_name }}:latest-${{ matrix.platform }}"
          
          # Build using Quarkus
          quarkus image build --native \
          -Dquarkus.native.container-build=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=docker.io \
          -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.DOCKER_TOKEN }} \
          -Dquarkus.container-image.image=${{ steps.prep.outputs.image_name }}:${{ github.event.inputs.version }}-${{ matrix.platform }} \
          -Dquarkus.container-image.additional-tags="latest-${{ matrix.platform }}" \
          -Dquarkus.container-image.labels.\"org.opencontainers.image.created\"="${{ steps.prep.outputs.created }}" \
          -Dquarkus.container-image.labels.\"org.opencontainers.image.revision\"="${{ github.sha }}"
          
          # Verify the image exists locally
          echo "Verifying local images:"
          docker images | grep ${{ steps.prep.outputs.image_name }}
          
          # Push explicitly as a backup
          echo "Pushing image explicitly with Docker CLI:"
          docker push ${IMAGE_TAG} || echo "Warning: Docker push via CLI failed"
          docker push ${LATEST_TAG} || echo "Warning: Latest tag push via CLI failed"

      # Verify push to Docker Hub
      - name: Verify Push to Docker Hub
        run: |
          echo "Verifying push to Docker Hub for ${{ steps.prep.outputs.image_name }}"
          # Can add commands to query Docker Hub API to verify the image exists
          # For simple verification, you can just echo the image URL
          echo "Image should be available at: docker.io/${{ steps.prep.outputs.image_name }}:${{ github.event.inputs.version }}-${{ matrix.platform }}"
          echo "Latest tag should be available at: docker.io/${{ steps.prep.outputs.image_name }}:latest-${{ matrix.platform }}"
