name: Docker build and push

# Define the events that trigger the workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (M.m.p)
        required: true

jobs:
  docker:
    # Define the operating systems and architectures to run the job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare metadata and timestamps
      - name: Prepare
        id: prep
        run: |
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "image_name=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

      # Set up GraalVM environment
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.TOKEN_GITHUB }}
          native-image-job-reports: 'true'

      # Install JBang and Quarkus CLI
      - name: Install JBang and Quarkus CLI
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
          echo "PATH=$PATH:/home/runner/.jbang/bin" >> $GITHUB_ENV

      # Verify the installation of Quarkus CLI
      - name: Verify Quarkus CLI installation
        run: quarkus --version

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the native image and push the Docker image
      - name: Build Native Image and Push Docker Image
        run: |
          echo "Building image for platform: ${{ matrix.platform }}"
          # We still build with platform suffix for internal reference
          PLATFORM_TAG="${{ steps.prep.outputs.image_name }}:${{ github.event.inputs.version }}-${{ matrix.platform }}"
          
          # Build using Quarkus
          quarkus image build --native \
          -Dquarkus.native.container-build=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=docker.io \
          -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.DOCKER_TOKEN }} \
          -Dquarkus.container-image.image=${{ steps.prep.outputs.image_name }}:${{ github.event.inputs.version }}-${{ matrix.platform }} \
          -Dquarkus.container-image.labels.\"org.opencontainers.image.created\"="${{ steps.prep.outputs.created }}" \
          -Dquarkus.container-image.labels.\"org.opencontainers.image.revision\"="${{ github.sha }}"
          
          # Verify the image exists locally
          echo "Verifying local images:"
          docker images | grep ${{ steps.prep.outputs.image_name }}
          
          # Push explicitly as a backup
          echo "Pushing image explicitly with Docker CLI:"
          docker push ${PLATFORM_TAG} || echo "Warning: Docker push via CLI failed"

  create-manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          echo "image_name=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create and push Docker manifest for multi-arch support
        run: |
          VERSION="${{ github.event.inputs.version }}"
          IMAGE_NAME="${{ steps.prep.outputs.image_name }}"
          
          # Enable experimental features for manifest command
          export DOCKER_CLI_EXPERIMENTAL=enabled
          
          # Create and push the version manifest
          docker manifest create ${IMAGE_NAME}:${VERSION} \
            ${IMAGE_NAME}:${VERSION}-amd64 \
            ${IMAGE_NAME}:${VERSION}-arm64
            
          docker manifest push ${IMAGE_NAME}:${VERSION}
          
          # Create and push the latest manifest
          docker manifest create ${IMAGE_NAME}:latest \
            ${IMAGE_NAME}:${VERSION}-amd64 \
            ${IMAGE_NAME}:${VERSION}-arm64
            
          docker manifest push ${IMAGE_NAME}:latest
          
          echo "Multi-architecture manifests created and pushed:"
          echo "- ${IMAGE_NAME}:${VERSION}"
          echo "- ${IMAGE_NAME}:latest"
